---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::ItemStatus
## it defines mappings from voyager.item_status_type to koha.items.*
##

#Voyager.ITEM_STATUS_TYPE
#ITEM_STATUS_DESC,                    ITEM_STATUS_TYPE
Not Charged:            ''           # 1
Charged:                ''           # 2
Renewed:                ''           # 3
Overdue:                ''           # 4
Recall Request:         ''           # 5
Hold Request:           ''           # 6 - #varauspyynto, jonka pitaisi kohdistua nimekkeelle tai varauskokoelmaan.
On Hold:                ''           # 7 - #Varaushyllyssa oleva
In Transit:             ''           # 8
In Transit Discharged:  ''           # 9 - #kuljetuksessa kotitoimipaikkaan palautuksen jalkeen
In Transit On Hold:     ''           # 10 - #kuljetuksessa noutopaikkaan
Discharged:             ''           # 11
Missing:                itemlost=4   # 12
Lost--Library Applied:  itemlost=1   # 13
Lost--System Applied:   itemlost=2   # 14
Claims Returned:        itemlost=4   # 15
Damaged:                damaged=1    # 16
Withdrawn:              withdrawn=1  # 17
At Bindery:             notforloan=3 # 18 - #HAMKilla tassa on henkilokuntakokoelmaa (muilla kirjastoilla arvo olisi 3 eli atbindery)
Cataloging Review:      notforloan=-4 # 19
Circulation Review:     notforloan=5 # 20
Scheduled:              ''           # 21 - #Ei kaytossa
In Process:             notforloan=-2 # 22 - #Hankinnan kautta saapuneiksi kasitellyt
Call Slip Request:      ''           # 23 - #aineistopyynto, pitaisi konvertoida nidekohtaiseksi varaukseksi
Short Loan Request:     ''           # 24 - #ei kaytossa
Remote Storage Request: ''           # 25 - #Ei kaytossa
_DEFAULT_: warning()
