---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::LocationId
## it defines mappings from voyager.location_id column to Koha's shelving_location and branchcode
##

##
## ref(101) - Refer another value instead.
##
## Used to alias various values to make accessing this table with different values from different data sources.
## Mainly the MARC-records refer using string-key, and other parts refer with the id.

#Voyager.LOCATION -table
#location_id,location_code,       #location_name

#branchLoc sets the following attributes:
#       branchcode, shelving_location, collection_code, sub_location, item.itemtype, item.notforloan-status
1: branchLoc(TK, REVIEW) #"REVIEW","REVIEW","REVIEW","REVIEW","Y","N","1","0"
REVIEW: ref(1)
2: branchLoc(TK, LEH) #"Lehdet","Lehdet","Lehdet","Lehdet","Y","N","1","93"
Lehdet: ref(2)
3: branchLoc(TK, VAR) #"Varasto","Varasto","Varasto","Varasto","Y","N","1","2506"
Varasto: ref(3)
4: branchLoc(TK, TIL, SUOMEN) #"FItilastot","Suomen tilastot","Suomen tilastot","FItilastot","Y","N","1","9052"
FItilastot: ref(4)
5: branchLoc(TK, TIL, MAITTAIN) #"Tilastot","Maittaiset tilastot","Maittaiset tilastot","Tilastot","Y","N","1","2453"
Tilastot: ref(5)
6: branchLoc(TK, KIR) #"Kirjat","Tietokirjat","Tietokirjat","Kirjat","Y","N","1","5130"
Kirjat: ref(6)
7: branchLoc(TK, REF) #"Ref","Hakuteokset","Hakuteokset (Ei lainata)","Ref","Y","N","1","528"
Ref: ref(7)
8: branchLoc(TK, TIL, KV) #"KVtilastot","Kansainv<E4>liset tilastot","Kansainv<E4>liset tilastot","KVtilastot","Y","N","1","4990"
KVtilastot: ref(8)
9: branchLoc(TK, LAI) #"Lainaus","Lainaus","Lainaus",,,"Y","1","0"
Lainaus: ref(9)
10: branchLoc(TK, KIR,,,-1) #"Hankinta","Hankinta","Hankinta",,,"Y","1","0"
Hankinta: ref(10)
11: branchLoc(TK, KIR,,,4) #"Luetteloin","Luettelointi","Luettelointi",,,"Y","1","0"
Luetteloin: ref(11)
12: branchLoc(TK, VER) #"Verkkoj","Verkkojulkaisut","Verkkojulkaisut","Verkkoj",,"N","1","2063"
Verkkoj: ref(12)
13: branchLoc(TK, TIL, YKSKT) #"TilYks","Tilastoyksikot","Tilastoyksikot",,,"N","1","0"
TilYks: ref(13)
14: branchLoc(TK, ART, EILIN) #"EiLindaan","EiLindaan","Artikkeli",,,"Y","1","0"
EiLindaan: ref(14)
15: branchLoc(TK, ART) #"Artikkelit","Artikkelit","Artikkelit",,,"N","1","7103"
Artikkelit: ref(15)
16: branchLoc(TK, VIR) #"Virk","Virkakirjat (Ei lainata)","Virkakirjat (Ei lainata)","Virk",,"N","1","493"
Virk: ref(16)

_DEFAULT_: branchLoc(TK, KONVERSIO, ERROR, ERROR) #By default, print a warning and use defaults )
