---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::PatronStatistics
## it defines mappings from voyager.patron_stat_id -column to Koha's ExtendedPatronAttributes-feature repeatable attribute 'statistic'
##

# Maybe these should be the koha.borrowers.categorycode (the category of the user)
# not some statistical groupings.
# These look very much like user account types.

#Asiakkaiden tilastoryhmissä (STAT_CAT Statistinen ryhmittely) pitäisi käyttää auktorisoituja arvoja. Lisäsin tilastoryhmät Auktorisoiduiksi arvoiksi nimeltä PATRON_STAT_GROUPS

#Mapataan patron_stat_coden mukaan PATRON_STAT_GROUPS arvoihin:
#PATRON_STAT_ID,PATRON_STAT_CODE,PATRON_STAT_DESC
1: TIL #,"Tilastokeskus"
2: STU #,"Opiskelija"
3: OPE #,"Opetus Tutkimus"
4: YKS #,"Yksityishenkilo"
5: KAU #,"Kaukopalvelu"
6: ELI #,"Elinkeinoelama"
7: JUL #,"Julkishallinto"
8: MUU #,"Muu"
