---

##
## IN THIS FILE
##
## The main configurations for MMT Voyager
##
##
## Configurations are introduced in the same order as they are needed by the migration tools

### 1) Data export phase
## Voyager DB dumps are fetched and delivered for the data transformation phase

# Absolute/full path to the script used to extract data from the VoyagerDB-server into the Koha-server.
# See the extract-dir for example implementations.
exportPipelineScript: '/home/koha/MMT-Voyager/secret/voyagerToKoha_fetchDataViaSSHJumpHost.sh'

importPipelineScript: '/home/koha/MMT-Voyager/secret/transformerToKoha_loadDataViaSSHJumpHosts.sh'

# From where the files exported from Voyager are found?
voyagerExportDir: /home/koha/MMT-Voyager/VoyagerExports

### 2) Data transformation phase
## Exported DB rows are mangled into Koha-objects

# Where the built library system objects are stored to be transported to Koha?
kohaImportDir: /home/koha/MMT-Voyager/KohaImports

# When migration Patrons, from which hetula ssn id we start generating anonymized ssn-keys?
# Finding the biggest ssn.id from Hetula, and incrementing it by a few thousands is a relatively safe bet.
# This is used to generate a separate list containing only Patron ssns and their Hetula ssn.ids.
# Patrons' ssn is replaced with the anonymized Hetula-key
hetulaStartingId: 1

# The Hetula ssn.id is formatted based on this pattern in Koha.borrowers_attributes->code=ssn
kohaHetulaKeyPattern: ssn0000000000

defaultReplacementPrice: 25

patronHomeLibrary: HAMK

holdingsTransformationModule: HAMK

workers: 1

